---
title: "carbontracking_subsetting"
author: "BGF"
date: "2/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hector)
library(ggplot2)
```


``` {r setup.core}
inifile <- file.path(system.file('input', package = 'hector'),
                     'hector_ssp245.ini')
core <- newcore(inifile)
fetchvars(core, NA, TRACKING_DATE())
```

``` {r set.date}
setvar(core, NA, TRACKING_DATE(), 1750, "(unitless)")
fetchvars(core, NA, TRACKING_DATE())
invisible(reset(core))
run(core)
```

``` {r hector.define_functions}
tracking_results <- function(inifile, start, stop, tracking, scenarioName) {
  # Establish core, turn on tracking, run core
  core <- newcore(inifile)
  setvar(core, NA, TRACKING_DATE(), tracking, "(unitless)")
  
  reset(core)
  run(core)
  
  # Get results, filter by correct years, add columns containing the amount of carbon by source and the given scenario name
  results <- get_tracking_data(core)
  results <- subset(results, year >= start)
  results <- subset(results, year <= stop)
  results$source_amount <- results$source_fraction * results$pool_value
  results$scenario_name <- scenarioName
  
  return(results)
}
AF_calc <- function(start, results, stop) {
  
  # Isolate the atmos_c pool and earth_c source in start/end years  
  atm_c <- subset(results, results$pool_name == "atmos_c")
  atm_c <- subset(atm_c, atm_c$source_name == "earth_c")
  
  atm_c1 <- subset(atm_c, year == start)
  atm_c2 <- subset(atm_c, year == stop)
  atm_c <- rbind(atm_c1, atm_c2)
  
  # Calculate atmospheric uptake of Earth carbon
  atm_c <- tail(atm_c$source_amount, n = 1) - head(atm_c$source_amount, n = 1)
  # Isolate earth_c pool and source in start/end years
  earth_c_loss <- subset(results, results$pool_name == "earth_c")
  earth_c_loss <- subset(earth_c_loss, earth_c_loss$source_name == "earth_c")
  e_c1 <- subset(earth_c_loss, year == start)
  e_c2 <- subset(earth_c_loss, year == stop)
  earth_c_loss <- rbind(e_c1, e_c2)
  
  # Calculate change in Earth carbon
  earth_c_loss <- head(earth_c_loss$source_amount, n = 1) - tail(earth_c_loss$source_amount, n = 1)
  
  # Airborne fraction calculation
  AF <- atm_c / earth_c_loss
  
  return(AF)
}
```