library(ggplot2)
library(gapminder)
library(dplyr)
summary(gapminder)
print(gapminder)
gapminder %>%  filter(country=="France" , year %in% c(1982,1987)) %>% summarise(mean(gdpPercap)) 
gapminder %>% filter(continent == "Europe") %>% group_by(country) %>% summarise(mean(lifeExp))
gapminder %>% filter(continent=="Europe") %>% group_by(year) %>% summarise(weighted.mean(lifeExp)) %>% ggplot(aes(x=year,y=lifeExp,size=lifeExp))+geom_point()+ggtitle("Mean lifeExp for Europe")
gapminder %>% count(country)                                                                     
gapminder %>% filter(continent=="Europe") %>% group_by(year) %>% summarise(mean_lifeExp=weighted.mean(lifeExp,pop))%>% ggplot(aes(x=year,y=mean_lifeExp,size=mean_lifeExp))+geom_point()+ggtitle("Mean lifeExp for Europe")
length(unique(gapminder$country))
